### ISSUE TITLE
Adapter API request failed

### ISSUE THREAD

**Issue by jasonsbrooks** [judoscale/judoscale-python#37]
I've consistently been seeing errors in my Heroku logs to the tune of:

> WARNING - [judoscale] Adapter API request failed - HTTPSConnectionPool(host='adapter.judoscale.com', port=443): Read timed out. (read timeout=5)

Is this anything to be concerned about? Is something in my setup potentially preventing Heroku from hitting the judoscale API, or are these errors expected from time to time? I just want to make sure the request is ever succeeding and these are 1-off errors instead of the other way around.

**Comment by adamlogic** [comment]
I'm not seeing failed requests on my side, so I'm not sure what's causing them. If you email support at judoscale.com and include the name of your Heroku app, I will make sure everything is working as expected.

**Comment by jasonsbrooks** [comment]
Closing this out as @adamlogic followed up with us offline and pointed out it's actually due to our logging infrastructure set up. Thanks for all the time helping us debug!
