### ISSUE TITLE
Default config for non heroku environments

### ISSUE THREAD

**Issue by jasonsbrooks** [judoscale/judoscale-python#59]
The default config for non Heroku environments is currently set as follows:
https://github.com/judoscale/judoscale-python/blob/e101123c8fc29d61b71de67cfa1dcee194ee7e4b/judoscale/core/config.py#L53

so `API_BASE_URL` is set as an empty string.

The code that determines if Judoscale should run, though, seems to compare `API_BASE_URL` against `None`:

https://github.com/judoscale/judoscale-python/blob/e101123c8fc29d61b71de67cfa1dcee194ee7e4b/judoscale/django/apps.py#L20

We've been seeing Judoscale attempting to run locally on our dev machines, and pretty sure it's because this check is returning True.

Should the default config instead return `return cls(None, None, env)` so the `API_BASE_URL` is set to None instead of ""? Or alternatively should the check be `if judoconfig["API_BASE_URL"]:`? Happy to put up a pull request if this seems reasonable.

**Comment by karls** [comment]
Hey @jasonsbrooks,

Thanks for this bug report. I'm able to reproduce this locally and I'm going to patch this today.

**Comment by jasonsbrooks** [comment]
Awesome, thanks so much @karls !

**Comment by karls** [comment]
Hey @jasonsbrooks,

I've just released [1.4.1](https://pypi.org/project/judoscale/1.4.1/), which should fix the issue you're seeing. 🙌🏻
