### ISSUE TITLE
Remove `is_web_instance` logic and `service_type` property

### ISSUE THREAD

**Issue by adamlogic** [judoscale/judoscale-python#66]
`RuntimeContainer` has a `service_type` property that's either "web" or "worker". The only place we use this property is in the `is_web_instance` method, and the only purpose of that method is to avoid redundant metrics from being reported on worker containers.

This is not necessary, though, because worker containers won't have web metrics to report. The `WebMetricsCollected` can be allowed to run on worker containers, and it'll essentially be a no-op.

**Comment by karls** [comment]
Fixed in #67.
