### ISSUE TITLE
Unable to find `published_at` in task properties when TRACK_BUSY_JOBS is enabled

### ISSUE THREAD

**Issue by ashleyxue529** [judoscale/judoscale-python#69]
My old setup worked fine (django, celery, redis on Heroku) with Judoscale, but I recently tried turning on this flag to see more info in the Judoscale UI for my worker fynos:
```
judoscale_celery(app, extra_config={"CELERY": {"TRACK_BUSY_JOBS": True}})
```

But immediately started seeing errors around `KeyError: 'id'` coming from [here](https://github.com/judoscale/judoscale-python/blob/d0e0fed5206f12b08bd69fa0f002cf834a35f293/judoscale/celery/collector.py#L126-L135). 

My env is setup using the steps here: https://github.com/judoscale/judoscale-python#using-judoscale-with-celery-and-redis, so I'm not really sure what I might be missing... Any pointers would be much appreciated, thank you!

**Comment by adamlogic** [comment]
Thanks for the report! Could you share your log output up to and including the error? You can email it to Judoscale support if you want to keep it private.
