### ISSUE TITLE
Support Django 5.0

### ISSUE THREAD

**Issue by collindutter** [judoscale/judoscale-python#80]
Django is currently [version locked](https://github.com/judoscale/judoscale-python/blob/ef1536faf81e5e5cf46e966ff66f0c8f6db3f549/pyproject.toml#L24) to `<5.0.0`, preventing usage of this package on [Django 5](https://docs.djangoproject.com/en/5.0/releases/5.0/).

Are there any plans to support Django 5 in the future?

Thanks for the great product and library!

**Comment by karls** [comment]
Thanks for notifying about this, @collindutter.

I don't think there is anything in Django 5 that's stopping `judoscale-python` from supporting it. @adamlogic I've created a PR (#81) to expand support Django version range to cover Django 5.x.x as well.

**Comment by adamlogic** [comment]
Thanks @karls!! I just released v1.7.0 with support for Django 5.
