### ISSUE TITLE
SIGTERM handling in Reporter breaks FastAPI/uvicorn reloading

### ISSUE THREAD

**Issue by Taytay** [judoscale/judoscale-python#92]
First, hey @adamlogic, and thanks for JudoScale!

When we run FastAPI/uvicorn with reloading set to true, our app was hanging when uvicorn tried to reload. It turns out that simple importing the reporter class from core/reporter.py would cause that behavior. (We don't actually import that class directly of course, but do import `FastAPIRequestQueueTimeMiddleware`, which in turn imports the reporter, but the bug is with the reporter file).

Upon further investigation, I narrowed it down to the SIGTERM handling:
https://github.com/judoscale/judoscale-python/blob/1132338512767ba802ffa4b4c85d2d7b7402e7f2/judoscale/core/reporter.py#L139

I believe that this is actually _overriding_ whatever SIGTERM handling is already present. Uvicorn uses SIGTERM as a way to shut down its current worker thread as part of reloading the server, so this line is stealing its ability to do so! If you add some code to ensure you pass the call on to existing handlers, FastAPI works like a champ again!

Here's my suggested replacement code:
```
previous_handler = signal.getsignal(signal.SIGTERM)

def graceful_shutdown(signum, frame):
    reporter.signal_handler(signum, frame)
    # If there was a previous handler and it's not SIG_DFL or SIG_IGN, call it
    if callable(previous_handler) and previous_handler not in (signal.SIG_DFL, signal.SIG_IGN):
        previous_handler(signum, frame)
    else:
        # If no previous handler, use default behavior (exit the process)
        signal.default_int_handler(signum, frame)

signal.signal(signal.SIGTERM, graceful_shutdown)

```

The repro for this bug is pretty simple.

Create your app.py as follows:
```
from fastapi import FastAPI
# this is the problem line:
from judoscale.core.reporter import reporter

app = FastAPI()

```

Then, run it in dev mode of fastAPI: `fastapi dev ./app.py`

Now, save the app.py file and it will tell you it detected a change and will reload...
But at that point it hangs!

If you remove the import, things work again. Or, if you replace the sigterm handling with the code above, it also works.

If, like me, you need to fix this in a hurry, and don't want to fork judoscale-python, I've also found this (hack) to work:
```python

def import_judoscale():
    import signal

    previous_handler = signal.getsignal(signal.SIGTERM)

    from judoscale.asgi.middleware import FastAPIRequestQueueTimeMiddleware
    from judoscale.core.reporter import reporter

    def graceful_reporter_shutdown(signum, frame):
        reporter.signal_handler(signum, frame)
        # If there was a previous handler and it's not SIG_DFL or SIG_IGN, call it
        if callable(previous_handler) and previous_handler not in (signal.SIG_DFL, signal.SIG_IGN):
            previous_handler(signum, frame)
        else:
            # If no previous handler, use default behavior (exit the process)
            signal.default_int_handler(signum, frame)

    # fix the SIGTERM handler
    signal.signal(signal.SIGTERM, graceful_reporter_shutdown)

    return FastAPIRequestQueueTimeMiddleware


FastAPIRequestQueueTimeMiddleware = import_judoscale()


```

**Comment by adamlogic** [comment]
Hey @Taytay, great to hear from you! So y'all are using Python now, eh? 😄 

Thanks for the detailed report, repro, and suggested fix! @carlosantoniodasilva and I will dig into this next week!

**Comment by Taytay** [comment]
Hah! Yeah, AI dabbling == Python these days. But, they let me add types if I _want_ to, so I don't have to hold my nose too much ;)

We're enjoying Judoscale so far on this project. It's working like a champ!

**Comment by adamlogic** [comment]
Your suggested fix worked like a charm! Thanks again!
